// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SegenApi.DbServices;

#nullable disable

namespace SegenApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SegenApi.Models.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7672e9ae-7928-4048-955b-e34b18c1000d"),
                            CreatedAt = new DateTime(2023, 10, 3, 12, 40, 43, 977, DateTimeKind.Utc).AddTicks(7731),
                            Description = "The Hitchhiker's Guide to the Galaxy is a comic science fiction series created by Douglas Adams that has become popular among fans of the genre and members of the scientific community.",
                            ModifiedAt = new DateTime(2023, 10, 3, 12, 40, 43, 977, DateTimeKind.Utc).AddTicks(7734),
                            Name = "The Hitchhiker's Guide to the Galaxy",
                            Price = 7.99m
                        },
                        new
                        {
                            Id = new Guid("ad2683b0-a85c-4c33-9d5f-02229976ef68"),
                            CreatedAt = new DateTime(2023, 10, 3, 12, 40, 43, 977, DateTimeKind.Utc).AddTicks(7742),
                            Description = "The Restaurant at the End of the Universe (1980, ISBN 0-345-39181-0) is the second book in the Hitchhiker's Guide to the Galaxy comedy science fiction trilogy by Douglas Adams, and is a sequel.",
                            ModifiedAt = new DateTime(2023, 10, 3, 12, 40, 43, 977, DateTimeKind.Utc).AddTicks(7742),
                            Name = "The Restaurant at the End of the Universe",
                            Price = 7.99m
                        },
                        new
                        {
                            Id = new Guid("0dcfec44-8c86-47b0-802c-7820971d58bf"),
                            CreatedAt = new DateTime(2023, 10, 3, 12, 40, 43, 977, DateTimeKind.Utc).AddTicks(7744),
                            Description = "Life, the Universe and Everything (1982, ISBN 0-345-39182-9) is the third book in the five-volume Hitchhiker's Guide to the Galaxy science fiction trilogy by British writer Douglas Adams.",
                            ModifiedAt = new DateTime(2023, 10, 3, 12, 40, 43, 977, DateTimeKind.Utc).AddTicks(7744),
                            Name = "Life, the Universe and Everything",
                            Price = 7.99m
                        },
                        new
                        {
                            Id = new Guid("cd3f30e0-3cea-4af5-b08e-910fcac4ed3b"),
                            CreatedAt = new DateTime(2023, 10, 3, 12, 40, 43, 977, DateTimeKind.Utc).AddTicks(7746),
                            Description = "So Long, and Thanks for All the Fish is the fourth book of the Hitchhiker's Guide to the Galaxy \"trilogy\" written by Douglas Adams. Its title is the message left by the dolphins when they departed Planet Earth just before it was demolished to make way for a hyperspace bypass, as described in The Hitchhiker's Guide to the Galaxy.",
                            ModifiedAt = new DateTime(2023, 10, 3, 12, 40, 43, 977, DateTimeKind.Utc).AddTicks(7746),
                            Name = "So Long, and Thanks for All the Fish",
                            Price = 7.99m
                        },
                        new
                        {
                            Id = new Guid("45ac40a4-bba5-4ccf-b7a5-70a22be511e7"),
                            CreatedAt = new DateTime(2023, 10, 3, 12, 40, 43, 977, DateTimeKind.Utc).AddTicks(7748),
                            Description = "Mostly Harmless is a 1992 novel by Douglas Adams and the fifth book in the Hitchhiker's Guide to the Galaxy series. It is described on the cover of the first editions as \"The fifth book in the increasingly inaccurately named Hitchhikers Trilogy\".",
                            ModifiedAt = new DateTime(2023, 10, 3, 12, 40, 43, 977, DateTimeKind.Utc).AddTicks(7748),
                            Name = "Mostly Harmless",
                            Price = 7.99m
                        },
                        new
                        {
                            Id = new Guid("1666dbfe-c9d6-42c9-9e47-2458fea6add0"),
                            CreatedAt = new DateTime(2023, 10, 3, 12, 40, 43, 977, DateTimeKind.Utc).AddTicks(7752),
                            Description = "And Another Thing... is the sixth and final installment of Douglas Adams' The Hitchhiker's Guide to the Galaxy \"trilogy\". The book, written by Eoin Colfer, author of the Artemis Fowl series, was published on the thirtieth anniversary of the first book, 12 October 2009, in hardback.",
                            ModifiedAt = new DateTime(2023, 10, 3, 12, 40, 43, 977, DateTimeKind.Utc).AddTicks(7752),
                            Name = "And Another Thing...",
                            Price = 7.99m
                        },
                        new
                        {
                            Id = new Guid("4c4a3f44-3f5f-48c9-87c9-7ee1e9e09648"),
                            CreatedAt = new DateTime(2023, 10, 3, 12, 40, 43, 977, DateTimeKind.Utc).AddTicks(7755),
                            Description = "some description for test book 1",
                            ModifiedAt = new DateTime(2023, 10, 3, 12, 40, 43, 977, DateTimeKind.Utc).AddTicks(7755),
                            Name = "Test book 1",
                            Price = 7.99m
                        },
                        new
                        {
                            Id = new Guid("587efa1f-770d-4ae8-a6bf-4ae5e8450cac"),
                            CreatedAt = new DateTime(2023, 10, 3, 12, 40, 43, 977, DateTimeKind.Utc).AddTicks(7765),
                            Description = "some description for test book 1",
                            ModifiedAt = new DateTime(2023, 10, 3, 12, 40, 43, 977, DateTimeKind.Utc).AddTicks(7766),
                            Name = "Test book 2",
                            Price = 7.99m
                        },
                        new
                        {
                            Id = new Guid("9a9ea663-0740-4bac-9596-0cbcf5b864d1"),
                            CreatedAt = new DateTime(2023, 10, 3, 12, 40, 43, 977, DateTimeKind.Utc).AddTicks(7772),
                            Description = "some description for test book 1",
                            ModifiedAt = new DateTime(2023, 10, 3, 12, 40, 43, 977, DateTimeKind.Utc).AddTicks(7772),
                            Name = "Test book 3",
                            Price = 7.99m
                        },
                        new
                        {
                            Id = new Guid("51c2ae99-fe9a-4c4a-9412-f179e079af13"),
                            CreatedAt = new DateTime(2023, 10, 3, 12, 40, 43, 977, DateTimeKind.Utc).AddTicks(7774),
                            Description = "some description for test book 1",
                            ModifiedAt = new DateTime(2023, 10, 3, 12, 40, 43, 977, DateTimeKind.Utc).AddTicks(7774),
                            Name = "Test book 4",
                            Price = 7.99m
                        },
                        new
                        {
                            Id = new Guid("ab40a95e-40a8-437e-89f3-0eb953d54618"),
                            CreatedAt = new DateTime(2023, 10, 3, 12, 40, 43, 977, DateTimeKind.Utc).AddTicks(7776),
                            Description = "some description for test book 1",
                            ModifiedAt = new DateTime(2023, 10, 3, 12, 40, 43, 977, DateTimeKind.Utc).AddTicks(7776),
                            Name = "Test book 5",
                            Price = 7.99m
                        },
                        new
                        {
                            Id = new Guid("6f8b7936-6810-48d1-bf1b-20717b1bc4e4"),
                            CreatedAt = new DateTime(2023, 10, 3, 12, 40, 43, 977, DateTimeKind.Utc).AddTicks(7777),
                            Description = "some description for test book 1",
                            ModifiedAt = new DateTime(2023, 10, 3, 12, 40, 43, 977, DateTimeKind.Utc).AddTicks(7778),
                            Name = "Test book 6",
                            Price = 7.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
